//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class zahtjevi
    {
        public int ID { get; set; }
        public int Korisnici_ID { get; set; }
        public string OpisZahtjeva { get; set; }
        public Nullable<bool> Obradjen { get; set; }
        public Nullable<bool> Seen { get; set; }
        public bool DodatniZahtjev { get; set; }
        public Nullable<int> SifraZahtjeva { get; set; }
    
        public virtual korisnici korisnici { get; set; }
    }
}
