//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forme
{
    using System;
    using System.Collections.Generic;
    
    public partial class kartoni
    {
        public int ID { get; set; }
        public int ID_D { get; set; }
        public int ID_Pr { get; set; }
        public int ID_E { get; set; }
        public int ID_Ps { get; set; }
    
        public virtual radnici radnici { get; set; }
        public virtual radnici radnici1 { get; set; }
        public virtual radnici radnici2 { get; set; }
        public virtual radnici radnici3 { get; set; }
    }
}
