//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forme
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnici
    {
        public korisnici()
        {
            this.status_d = new HashSet<status_d>();
            this.status_e = new HashSet<status_e>();
            this.status_pr = new HashSet<status_pr>();
            this.status_ps = new HashSet<status_ps>();
            this.rasporedi = new HashSet<rasporedi>();
        }
    
        public int ID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int Lokacija_ID { get; set; }
        public bool Anonimnost { get; set; }
        public string DodatneOsobe { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
    
        public virtual lokacije lokacije { get; set; }
        public virtual ICollection<status_d> status_d { get; set; }
        public virtual ICollection<status_e> status_e { get; set; }
        public virtual ICollection<status_pr> status_pr { get; set; }
        public virtual ICollection<status_ps> status_ps { get; set; }
        public virtual ICollection<rasporedi> rasporedi { get; set; }
    }
}
