//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeHouse
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydbEntities : DbContext
    {
        public mydbEntities()
            : base("name=mydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<kartoni> kartoni { get; set; }
        public DbSet<korisnici> korisnici { get; set; }
        public DbSet<lokacije> lokacije { get; set; }
        public DbSet<radnici> radnici { get; set; }
        public DbSet<rasporedi> rasporedi { get; set; }
        public DbSet<status_d> status_d { get; set; }
        public DbSet<status_e> status_e { get; set; }
        public DbSet<status_pr> status_pr { get; set; }
        public DbSet<status_ps> status_ps { get; set; }
        public DbSet<zahtjevi> zahtjevi { get; set; }
    }
}
